background {
  path = /usr/share/backgrounds/shinobi-os/shinobi-night.png
  blur_passes = 2
  blur_size = 6
  color = rgba(1e1e2eff)
}

input-field {
  size = 250, 50
  position = 0, 0
  halign = center
  valign = center
  outline_thickness = 2
  fail_color = rgba(f38ba8ff)
}

label {
  text = $TIME
  color = rgba(cdd6f4ff)
  font_size = 32
  position = 0, 120
  halign = center
  valign = center
}

label {
  text = Shinobi OS
  color = rgba(cdd6f4cc)
  font_size = 16
  position = 0, -120
  halign = center
  valign = center
}
